"use strict";

// Catch unhandled errors
window.addEventListener("error", function(e) {
    var msg = "UNHANDLED: " + (e.message || String(e)) + " at " + (e.filename || "") + ":" + (e.lineno || "") + ":" + (e.colno || "");
    console.error(msg);
  });
  window.addEventListener("unhandledrejection", function(e) {
    var msg = "UNHANDLED REJECTION: " + (e.reason && (e.reason.message || e.reason.stack || String(e.reason)) || String(e));
    console.error(msg);
  });

(function () {

  // List of all scripts to load in order
  const SCRIPTS = [
    "src/utils/error.js",
    "src/utils/position.js",
    "src/input/pathfinder.js",
    "src/entities/condition.js",
    "src/entities/spellbook.js",
    "src/utils/casting-manager.js",
    "src/utils/__proto__.js",
    "src/utils/bitmap-font.js",
    "src/utils/font-manager.js",
    "src/utils/rgba.js",
    "src/ui/settings.js",
    "src/entities/state.js",
    "src/core/game-loop.js",
    "src/ui/status-bar.js",
    "src/core/database.js",
    "src/ui/fight-mode-selector.js",
    "src/ui/tooltip.js",
    "src/ui/interface.js",
    "src/network/packet-handler.js",
    "src/utils/enum.js",
    "src/audio/soundbit.js",
    "src/audio/soundtrace.js",
    "src/audio/sound-manager.js",
    "src/audio/voice-manager.js",
    "src/rendering/canvas.js",
    "src/rendering/outline-canvas.js",
    "src/rendering/light-canvas.js",
    "src/rendering/weather-canvas.js",
    "src/rendering/sprite-buffer.js",
    "src/utils/object-buffer.js",
    "src/utils/eventemitter.js",
    "src/core/gameclient.js",
    "src/rendering/minimap.js",
    "src/entities/outfit.js",
    "src/entities/thing.js",
    "src/utils/dataobject.js",
    "src/utils/bitflag.js",
    "src/utils/frame-group.js",
    "src/utils/clock.js",
    "src/ui/menus/menu.js",
    "src/ui/menus/menu-message.js",
    "src/ui/menus/menu-screen.js",
    "src/ui/menus/menu-friend-list.js",
    "src/ui/menus/menu-friend-window.js",
    "src/ui/menus/menu-chat-header.js",
    "src/ui/menus/menu-chat-body.js",
    "src/ui/menus/menu-container.js",
    "src/ui/menus/menu-minimap.js",
    "src/ui/menus/menu-minimap-pin.js",
    "src/ui/menus/menu-manager.js",
    "src/rendering/renderer.js",
    "src/rendering/renderer-light.js",
    "src/rendering/renderer-effects.js",
    "src/rendering/renderer-creature.js",
    "src/rendering/renderer-tile.js",
    "src/rendering/renderer-world.js",
    "src/rendering/renderer-custom.js",
    "src/network/network-manager.js",
    "src/utils/channel-manager.js",
    "src/ui/modals/modal-manager.js",
    "src/ui/window.js",
    "src/ui/window-friend.js",
    "src/ui/window-skill.js",
    "src/ui/window-battle.js",
    "src/ui/window-party.js",
    "src/ui/window-questtracker.js",
    "src/ui/window-manager.js",
    "src/ui/console-resizer.js",
    "src/rendering/debugger.js",
    "src/ui/screen-element-manager.js",
    "src/ui/screen-element.js",
    "src/ui/screen-element-character.js",
    "src/ui/screen-element-message.js",
    "src/ui/screen-element-floating.js",
    "src/entities/skills.js",
    "src/utils/animation.js",
    "src/utils/distance-animation.js",
    "src/utils/box-animation.js",
    "src/entities/item.js",
    "src/utils/fluid-container.js",
    "src/utils/book.js",
    "src/rendering/sprite.js",
    "src/utils/channel.js",
    "src/utils/private-channel.js",
    "src/utils/local-channel.js",
    "src/entities/friendlist.js",
    "src/entities/ignorelist.js",
    "src/utils/message.js",
    "src/utils/message-character.js",
    "src/input/keyboard.js",
    "src/input/mouse.js",
    "src/entities/slot.js",
    "src/entities/container.js",
    "src/entities/equipment.js",
    "src/ui/notification.js",
    "src/data/shop-data.js",
    "src/network/packet.js",
    "src/network/packetwriter.js",
    "src/network/packetreader.js",
    "src/network/protocol.js",
    "src/core/world.js",
    "src/entities/creature.js",
    "src/entities/player.js",
    "src/entities/chunk.js",
    "src/entities/tile.js",
    "src/ui/modals/modal.js",
    "src/ui/modals/modal-shop.js",
    "src/ui/modals/modal-payment.js",
    "src/ui/modals/modal-create-account.js",
    "src/ui/modals/modal-spellbook.js",
    "src/ui/modals/modal-hotkey.js",
    "src/ui/modals/modal-confirm.js",
    "src/ui/modals/modal-death.js",
    "src/ui/modals/modal-blessing.js",
    "src/ui/modals/modal-guild.js",
    "src/ui/modals/modal-house.js",
    "src/ui/modals/modal-house-manage.js",
    "src/ui/modals/modal-trade.js",
    "src/ui/modals/modal-enter-name.js",
    "src/ui/modals/modal-ignore-list.js",
    "src/ui/modals/modal-map.js",
    "src/ui/modals/modal-text.js",
    "src/ui/modals/modal-move-item.js",
    "src/ui/modals/modal-outfit.js",
    "src/ui/modals/modal-market.js",
    "src/ui/modals/modal-characters.js",
    "src/ui/modals/modal-chat.js",
    "src/ui/modals/modal-readable.js",
    "src/ui/modals/modal-offer.js",
    "src/ui/modals/modal-oracle.js",
    "src/ui/window-questlog.js",
    "src/core/event-queue.js",
    "src/utils/heap-event.js",
    "src/utils/binary-heap.js",
    "src/core/index.js",
    "src/ui/mobile-fullscreen.js"
  ];

  function loadNextScript(index) {
    if (index >= SCRIPTS.length) return;
    let src = SCRIPTS[index];
    let script = document.createElement("script");
    script.src = src;
    script.onload = function () { loadNextScript(index + 1); };
    script.onerror = function () { loadNextScript(index + 1); };
    document.body.appendChild(script);
  }

  loadNextScript(0);

})();
